version: '3.9'

services:
  app:
   build:
     context: .
     dockerfile: Dockerfile
   volumes:
    - .:/app
   ports:
    - 8000:8000
   image: registration-app
   container_name: app-container
   command: gunicorn simple_registration.wsgi:application --bind 0.0.0.0:8000
